#!/bin/bash
# Orchestrator Stop Hook: Auto-poll inbox, trigger gap-analysis
# Generated by Sigma Protocol

TARGET_DIR="/Users/dallionking/SSS Projects/SSS-Protocol"
INBOX="/Users/dallionking/SSS Projects/SSS-Protocol/.sigma/orchestration/inbox/orchestrator.json"
MAX_MESSAGES=50
KEEP_MESSAGES=25

# Read and check for unprocessed messages
if [ -f "$INBOX" ]; then
  # Count unprocessed messages
  UNPROCESSED=$(jq '[.messages[] | select(.processed == false)] | length' "$INBOX" 2>/dev/null || echo "0")
  
  if [ "$UNPROCESSED" -gt 0 ]; then
    echo ""
    echo "📬 ORCHESTRATOR INBOX: $UNPROCESSED new message(s)"
    echo "---"
    
    # Show new messages
    jq -r '.messages[] | select(.processed == false) | "  [\(.type)] from \(.from): \(.status // "no status")"' "$INBOX" 2>/dev/null
    
    # Check for completion messages - suggest gap-analysis
    COMPLETIONS=$(jq '[.messages[] | select(.processed == false and .type == "prd_complete")] | length' "$INBOX" 2>/dev/null || echo "0")
    if [ "$COMPLETIONS" -gt 0 ]; then
      echo ""
      echo "🔍 Fork(s) reported completion. Consider running: @gap-analysis"
    fi
    
    echo "---"
    echo "Use /hub:sync to process messages, or check: $INBOX"
    echo ""
  fi
  
  # Inbox cleanup: if > MAX_MESSAGES, summarize and keep KEEP_MESSAGES
  TOTAL_MESSAGES=$(jq '.messages | length' "$INBOX" 2>/dev/null || echo "0")
  if [ "$TOTAL_MESSAGES" -gt "$MAX_MESSAGES" ]; then
    echo "⚠️  Inbox has $TOTAL_MESSAGES messages (limit: $MAX_MESSAGES). Running cleanup..."
    # Keep the most recent KEEP_MESSAGES
    jq ".messages = .messages[-${KEEP_MESSAGES}:]" "$INBOX" > "$INBOX.tmp" && mv "$INBOX.tmp" "$INBOX"
    echo "✓ Kept most recent $KEEP_MESSAGES messages"
  fi
  
  # Context summarization: if inbox file > 500 lines, summarize older content
  MAX_LINES=500
  INBOX_LINES=$(wc -l < "$INBOX" 2>/dev/null || echo "0")
  if [ "$INBOX_LINES" -gt "$MAX_LINES" ]; then
    echo "⚠️  Inbox file has $INBOX_LINES lines (limit: $MAX_LINES). Consider manual summarization."
    echo "   Tip: Archive older messages to .sigma/orchestration/archive/"
  fi
fi

exit 0
