import { z } from 'zod';

// Schema for a posted reply
export const ReplySchema = z.object({
  id: z.number().int().optional(), // Auto-generated by DB
  accountId: z.string(),
  tweetId: z.string(),
  tweetAuthor: z.string(),
  tweetContent: z.string(),
  replyId: z.string().optional(), // ID of our reply tweet
  replyContent: z.string(),
  tone: z.enum(['educational', 'relatable', 'valueFirst', 'direct']),
  postedAt: z.date().optional(),
  engagementLikes: z.number().int().default(0),
  engagementReplies: z.number().int().default(0),
  engagementRetweets: z.number().int().default(0),
});

// Schema for rate limit tracking
export const RateLimitSchema = z.object({
  accountId: z.string(),
  date: z.string(), // YYYY-MM-DD format
  repliesCount: z.number().int().default(0),
  lastReplyAt: z.date().optional(),
});

// Schema for tweet relevance check result
export const RelevanceResultSchema = z.object({
  relevant: z.boolean(),
  confidence: z.number().min(0).max(100),
  reason: z.string(),
});

// Schema for a candidate tweet to reply to
export const CandidateTweetSchema = z.object({
  id: z.string(),
  text: z.string(),
  authorId: z.string(),
  authorUsername: z.string(),
  authorName: z.string().optional(),
  authorBio: z.string().optional(),
  authorFollowers: z.number().int().optional(),
  createdAt: z.date(),
  likeCount: z.number().int().optional(),
  replyCount: z.number().int().optional(),
  retweetCount: z.number().int().optional(),
  relevanceScore: z.number().min(0).max(100).optional(),
});

// Type exports
export type Reply = z.infer<typeof ReplySchema>;
export type RateLimit = z.infer<typeof RateLimitSchema>;
export type RelevanceResult = z.infer<typeof RelevanceResultSchema>;
export type CandidateTweet = z.infer<typeof CandidateTweetSchema>;

// Database row types (for SQL queries)
export interface ReplyRow {
  id: number;
  account_id: string;
  tweet_id: string;
  tweet_author: string;
  tweet_content: string;
  reply_id: string | null;
  reply_content: string;
  tone: string;
  posted_at: string;
  engagement_likes: number;
  engagement_replies: number;
  engagement_retweets: number;
}

export interface RateLimitRow {
  account_id: string;
  date: string;
  replies_count: number;
  last_reply_at: string | null;
}


