/**
 * State Management Types
 * Core state schema for Sigma Protocol workflow
 * @module @sigma-protocol/core/types/state
 */

/**
 * Current schema version for migration support
 */
export const STATE_SCHEMA_VERSION = "1.0.0" as const;

/**
 * Supported platform types
 */
export type PlatformType = "opencode" | "claude-code" | "cursor" | "factory-droid";

/**
 * Step completion status
 */
export type StepStatus = "pending" | "in_progress" | "completed" | "skipped" | "failed";

/**
 * HITL decision types
 */
export type HITLDecisionType = "approve" | "reject" | "modify" | "skip" | "defer";

/**
 * HITL decision made by user
 */
export interface HITLDecision {
  /**
   * Decision type
   */
  type: HITLDecisionType;

  /**
   * Optional feedback or modifications
   */
  feedback?: string;

  /**
   * Timestamp of decision
   */
  timestamp: string;

  /**
   * User who made the decision (if tracked)
   */
  userId?: string;
}

/**
 * Individual step state
 */
export interface StepExecutionState {
  /**
   * Step number (0-13, with 1.5 and 11.5 as decimals)
   */
  number: number;

  /**
   * Step name
   */
  name: string;

  /**
   * Current status
   */
  status: StepStatus;

  /**
   * Quality gate score (0-100)
   */
  score: number | null;

  /**
   * When step was started
   */
  startedAt: string | null;

  /**
   * When step was completed
   */
  completedAt: string | null;

  /**
   * Output files generated by this step
   */
  outputs: string[];

  /**
   * HITL decisions for this step
   */
  hitlDecisions: HITLDecision[];

  /**
   * Error message if step failed
   */
  error?: string;
}

/**
 * Overall workflow execution state
 */
export interface WorkflowExecutionState {
  /**
   * Currently active step
   */
  currentStep: number;

  /**
   * Individual step states
   */
  steps: Record<number, StepExecutionState>;

  /**
   * Workflow start time
   */
  startedAt: string | null;

  /**
   * Workflow completion time
   */
  completedAt: string | null;

  /**
   * Overall progress percentage (0-100)
   */
  progress: number;
}

/**
 * Pending HITL checkpoint
 */
export interface PendingHITL {
  /**
   * Unique checkpoint ID
   */
  checkpointId: string;

  /**
   * Associated step number
   */
  stepNumber: number;

  /**
   * Checkpoint type
   */
  type: string;

  /**
   * When checkpoint was created
   */
  createdAt: string;

  /**
   * Data to review
   */
  data: unknown;
}

/**
 * HITL state tracking
 */
export interface HITLState {
  /**
   * Pending checkpoints awaiting user decision
   */
  pending: PendingHITL[];

  /**
   * History of all HITL interactions
   */
  history: Array<{
    checkpointId: string;
    stepNumber: number;
    decision: HITLDecision;
  }>;
}

/**
 * Agent execution state
 */
export interface AgentState {
  /**
   * Currently active agent ID
   */
  activeAgentId: string | null;

  /**
   * Agent execution history
   */
  history: Array<{
    agentId: string;
    input: string;
    output: string;
    timestamp: string;
    success: boolean;
  }>;
}

/**
 * PRD tracking state
 */
export interface PRDState {
  /**
   * Generated PRD files
   */
  generated: Array<{
    id: string;
    path: string;
    stepNumber: number;
    createdAt: string;
  }>;

  /**
   * Ralph backlog JSON files
   */
  backlogs: Array<{
    phase: "prototype" | "implementation";
    path: string;
    totalStories: number;
    completedStories: number;
    createdAt: string;
  }>;
}

/**
 * State snapshot for rollback
 */
export interface StateSnapshot {
  /**
   * Snapshot ID
   */
  id: string;

  /**
   * When snapshot was created
   */
  createdAt: string;

  /**
   * Reason for snapshot
   */
  reason: string;

  /**
   * Step number at snapshot time
   */
  stepNumber: number;

  /**
   * Snapshot file path
   */
  path: string;
}

/**
 * State metadata
 */
export interface StateMetadata {
  /**
   * When state was first created
   */
  createdAt: string;

  /**
   * When state was last saved
   */
  lastSavedAt: string;

  /**
   * Platform that created/modified state
   */
  platform?: PlatformType;

  /**
   * Custom metadata
   */
  custom?: Record<string, unknown>;
}

/**
 * Complete Sigma Protocol state
 */
export interface SigmaState {
  /**
   * Schema version for migrations
   */
  version: typeof STATE_SCHEMA_VERSION;

  /**
   * Unique project identifier
   */
  projectId: string;

  /**
   * Project root path
   */
  projectPath: string;

  /**
   * Workflow execution state
   */
  workflow: WorkflowExecutionState;

  /**
   * HITL checkpoint state
   */
  hitl: HITLState;

  /**
   * Agent execution state
   */
  agents: AgentState;

  /**
   * PRD tracking state
   */
  prds: PRDState;

  /**
   * State snapshots for rollback
   */
  snapshots: StateSnapshot[];

  /**
   * State metadata
   */
  metadata?: StateMetadata;
}

/**
 * Create an empty initial state
 */
export function createInitialState(projectId: string, projectPath: string): SigmaState {
  const now = new Date().toISOString();

  return {
    version: STATE_SCHEMA_VERSION,
    projectId,
    projectPath,
    workflow: {
      currentStep: 0,
      steps: {},
      startedAt: null,
      completedAt: null,
      progress: 0,
    },
    hitl: {
      pending: [],
      history: [],
    },
    agents: {
      activeAgentId: null,
      history: [],
    },
    prds: {
      generated: [],
      backlogs: [],
    },
    snapshots: [],
    metadata: {
      createdAt: now,
      lastSavedAt: now,
    },
  };
}

/**
 * Validate state structure
 */
export function validateState(state: unknown): state is SigmaState {
  if (!state || typeof state !== "object") {
    return false;
  }

  const s = state as Record<string, unknown>;

  return (
    typeof s.version === "string" &&
    typeof s.projectId === "string" &&
    typeof s.projectPath === "string" &&
    typeof s.workflow === "object" &&
    typeof s.hitl === "object" &&
    typeof s.agents === "object" &&
    typeof s.prds === "object" &&
    Array.isArray(s.snapshots)
  );
}
