#!/usr/bin/env node

/**
 * SLAS Generator Module
 *
 * Generates hooks, skills, and rules from learned preferences.
 * Auto-creates artifacts based on distilled patterns.
 */

import fs from "fs-extra";
import path from "path";

/**
 * Hook templates based on pattern types
 */
const HOOK_TEMPLATES = {
  // Validate no hardcoded data (from repeated corrections)
  validateNoHardcodedData: {
    name: "validate-no-hardcoded-data.sh",
    type: "PreToolUse",
    matcher: "Edit|Write",
    condition: { glob: "**/*.{ts,tsx,js,jsx}" },
    script: `#!/bin/bash
# Auto-generated by SLAS: Validates no hardcoded data
# Based on repeated corrections about hardcoded values

FILE="$1"

if grep -qE '(localhost|127\\.0\\.0\\.1|hardcoded|TODO.*live)' "$FILE" 2>/dev/null; then
  echo "⚠️  Warning: Potential hardcoded value detected"
  echo "File: $FILE"
  grep -nE '(localhost|127\\.0\\.0\\.1|hardcoded|TODO.*live)' "$FILE" | head -5
  echo ""
  echo "Consider using environment variables or configuration."
fi
`
  },

  // Loop detector (from retry frustration patterns)
  loopDetector: {
    name: "loop-detector.sh",
    type: "PostToolUse",
    matcher: "Bash|Edit",
    script: `#!/bin/bash
# Auto-generated by SLAS: Detects potential retry loops
# Based on user frustration with repeated attempts

HISTORY_FILE="/tmp/slas-tool-history-$$"

# Track tool calls
echo "$(date +%s)" >> "$HISTORY_FILE"

# Check for rapid repeated calls
if [ -f "$HISTORY_FILE" ]; then
  RECENT=$(tail -10 "$HISTORY_FILE" | wc -l)
  if [ "$RECENT" -ge 5 ]; then
    FIRST=$(head -1 "$HISTORY_FILE")
    LAST=$(tail -1 "$HISTORY_FILE")
    DURATION=$((LAST - FIRST))

    if [ "$DURATION" -lt 30 ]; then
      echo "⚠️  Detected rapid retry pattern (5 attempts in <30s)"
      echo "Consider pausing to analyze the root cause."
    fi
  fi
fi

# Cleanup old history
find /tmp -name "slas-tool-history-*" -mmin +60 -delete 2>/dev/null
`
  },

  // Ship reminder (from focus drift patterns)
  shipReminder: {
    name: "ship-reminder.sh",
    type: "UserPromptSubmit",
    script: `#!/bin/bash
# Auto-generated by SLAS: Reminds about shipping deadlines
# Based on detected focus drift patterns

REMINDER_FILE="$CLAUDE_PROJECT_DIR/.slas-ship-reminder"

# Check if reminder is set
if [ -f "$REMINDER_FILE" ]; then
  DEADLINE=$(cat "$REMINDER_FILE")
  DAYS_LEFT=$(( ($(date -d "$DEADLINE" +%s 2>/dev/null || date -j -f "%Y-%m-%d" "$DEADLINE" +%s 2>/dev/null) - $(date +%s)) / 86400 ))

  if [ "$DAYS_LEFT" -le 14 ] && [ "$DAYS_LEFT" -gt 0 ]; then
    echo ""
    echo "⏰ Ship Reminder: $DAYS_LEFT days until deadline ($DEADLINE)"
    echo ""
  fi
fi
`
  }
};

/**
 * Skill templates based on pattern types
 */
const SKILL_TEMPLATES = {
  // Quick action skill (for high autonomy users)
  quickAction: {
    name: "quick-action.md",
    content: (patterns) => `---
name: quick-action
description: Execute common tasks without confirmation
generated_at: ${new Date().toISOString()}
---

# Quick Action Mode

When the user requests routine tasks, execute immediately without asking for confirmation.

## Auto-Execute Tasks
- File creation/modification within the project
- Running tests
- Git operations (add, commit with message)
- Installing dependencies
- Code formatting

## Always Confirm
- Destructive operations (delete, reset)
- Operations affecting remote (push, deploy)
- Changes to configuration files
- Operations with cost implications

## User Profile
- Autonomy Level: ${patterns.autonomy_level?.label || 'high'}
- Verbosity: ${patterns.communication?.verbosity || 'minimal'}
`
  },

  // Domain expert skill
  domainExpert: {
    name: "domain-context.md",
    content: (patterns) => {
      const expertise = patterns.domain_expertise || {};
      const topDomains = Object.entries(expertise)
        .sort(([,a], [,b]) => b - a)
        .slice(0, 5);

      return `---
name: domain-context
description: Apply domain-specific knowledge based on user's expertise
generated_at: ${new Date().toISOString()}
---

# Domain Context

This user frequently works with:

${topDomains.map(([domain, count]) => `
## ${domain.charAt(0).toUpperCase() + domain.slice(1)}
- Frequency: ${count} references
- Expertise: ${count > 50 ? 'Expert' : count > 20 ? 'Intermediate' : 'Familiar'}
- Apply: Best practices and advanced patterns
`).join("\n")}

## Interaction Guidelines
- Use domain-specific terminology without over-explanation
- Suggest advanced patterns when appropriate
- Reference relevant documentation when helpful
`;
    }
  }
};

/**
 * Generate a hook file from template
 * @param {Object} template - Hook template
 * @param {string} targetDir - Target directory
 * @returns {Promise<string>} - Path to generated file
 */
async function generateHook(template, targetDir) {
  const hooksDir = path.join(targetDir, ".claude", "hooks", "slas", "generated");
  await fs.ensureDir(hooksDir);

  const filePath = path.join(hooksDir, template.name);
  await fs.writeFile(filePath, template.script);
  await fs.chmod(filePath, 0o755);

  return filePath;
}

/**
 * Generate a skill file from template
 * @param {Object} template - Skill template
 * @param {Object} patterns - Distilled patterns
 * @param {string} targetDir - Target directory
 * @returns {Promise<string>} - Path to generated file
 */
async function generateSkill(template, patterns, targetDir) {
  const skillsDir = path.join(targetDir, ".claude", "skills", "developer-preferences");
  await fs.ensureDir(skillsDir);

  const content = typeof template.content === "function"
    ? template.content(patterns)
    : template.content;

  const filePath = path.join(skillsDir, template.name);
  await fs.writeFile(filePath, content);

  return filePath;
}

/**
 * Generate Cursor rules from patterns
 * @param {Object} patterns - Distilled patterns
 * @param {string} targetDir - Target directory
 * @returns {Promise<string>} - Path to generated file
 */
async function generateCursorRules(patterns, targetDir) {
  const rulesDir = path.join(targetDir, ".cursor", "rules");
  await fs.ensureDir(rulesDir);

  const autonomyLevel = patterns.autonomy_level?.label || "medium";
  const verbosity = patterns.communication?.verbosity || "standard";

  const content = `# SLAS Generated Preferences
# Auto-generated from ${patterns.sessions_analyzed || 0} sessions
# Last updated: ${new Date().toISOString()}

## Communication Style
${verbosity === "minimal" ? `
- Keep responses concise
- Avoid over-explanation
- Get to actionable items quickly
` : verbosity === "detailed" ? `
- Provide thorough explanations
- Include context and rationale
- Break down complex topics
` : `
- Balance brevity with clarity
- Explain when helpful
`}

## Autonomy Level: ${autonomyLevel}
${autonomyLevel === "high" ? `
- Execute routine tasks without confirmation
- Only ask about ambiguous requirements
- Proceed with best judgment
` : autonomyLevel === "low" ? `
- Confirm before making changes
- Explain proposed actions first
- Wait for explicit approval
` : `
- Use judgment for routine tasks
- Confirm significant changes
`}

## Frustration Patterns to Avoid
${(patterns.frustration_triggers || []).slice(0, 3).map(f =>
  `- ${f.trigger.slice(0, 60)}...`
).join("\n") || "- None detected"}

---
_Generated by SLAS. Run \`/session-distill\` to update._
`;

  const filePath = path.join(rulesDir, "slas-preferences.md");
  await fs.writeFile(filePath, content);

  return filePath;
}

/**
 * Generate OpenCode event hooks from patterns
 * @param {Object} patterns - Distilled patterns
 * @param {string} targetDir - Target directory
 * @returns {Promise<string[]>} - Paths to generated files
 */
async function generateOpenCodeHooks(patterns, targetDir) {
  const toolsDir = path.join(targetDir, ".opencode", "tools");
  await fs.ensureDir(toolsDir);

  // OpenCode uses a different hook format
  const hookConfig = {
    name: "slas-preferences",
    version: "1.0.0",
    events: {
      onStart: {
        inject: [
          "docs/sessions/preferences/developer-profile.yaml"
        ]
      }
    },
    rules: []
  };

  if (patterns.autonomy_level?.label === "high") {
    hookConfig.rules.push({
      type: "behavior",
      name: "auto-execute",
      description: "Execute routine tasks without confirmation"
    });
  }

  const filePath = path.join(toolsDir, "slas-preferences.json");
  await fs.writeJson(filePath, hookConfig, { spaces: 2 });

  return [filePath];
}

/**
 * Update CLAUDE.md with preferences section
 * @param {Object} patterns - Distilled patterns
 * @param {string} targetDir - Target directory
 * @returns {Promise<boolean>} - Success status
 */
async function updateClaudeMD(patterns, targetDir) {
  const claudeMdPath = path.join(targetDir, "CLAUDE.md");

  if (!(await fs.pathExists(claudeMdPath))) {
    return false;
  }

  let content = await fs.readFile(claudeMdPath, "utf-8");

  const preferencesSection = `
## Self-Learning Preferences (Auto-Generated)

> Last updated: ${new Date().toISOString().split("T")[0]} | Sessions analyzed: ${patterns.sessions_analyzed || 0} | Confidence: ${Math.round((patterns.confidence || 0.5) * 100)}%

### Key Behaviors
- Autonomy: ${patterns.autonomy_level?.label || "medium"} - ${patterns.autonomy_level?.label === "high" ? "Execute without asking for routine tasks" : "Confirm before significant changes"}
- Verbosity: ${patterns.communication?.verbosity || "standard"} - ${patterns.communication?.verbosity === "minimal" ? "Keep responses concise" : "Provide appropriate detail"}
- Domain Focus: ${Object.entries(patterns.domain_expertise || {}).slice(0, 3).map(([k,v]) => `${k} (${v})`).join(", ") || "General"}

### Avoid
${(patterns.frustration_triggers || []).slice(0, 3).map(f =>
  `- ${f.trigger.slice(0, 60)}...`
).join("\n") || "- No specific patterns detected"}

_Generated by SLAS. Run \`/session-distill\` to update._

`;

  // Check if section already exists
  const sectionMarker = "## Self-Learning Preferences";
  const sectionEnd = "\n_Generated by SLAS";

  if (content.includes(sectionMarker)) {
    // Replace existing section
    const startIdx = content.indexOf(sectionMarker);
    const endIdx = content.indexOf(sectionEnd, startIdx);

    if (endIdx !== -1) {
      const endOfSection = content.indexOf("\n\n", endIdx);
      content = content.slice(0, startIdx) +
                preferencesSection.trim() +
                content.slice(endOfSection !== -1 ? endOfSection : endIdx + sectionEnd.length + 50);
    }
  } else {
    // Add section before "## Skills" or at end
    const skillsIdx = content.indexOf("## Skills");
    if (skillsIdx !== -1) {
      content = content.slice(0, skillsIdx) + preferencesSection + "\n" + content.slice(skillsIdx);
    } else {
      content = content + "\n" + preferencesSection;
    }
  }

  await fs.writeFile(claudeMdPath, content);
  return true;
}

/**
 * Generate all artifacts from distillation results
 * @param {string} targetDir - Target project directory
 * @param {Object} results - Distillation results
 * @param {Object} options - Generation options
 * @returns {Promise<Object>} - Generation summary
 */
export async function generateArtifacts(targetDir, results, options = {}) {
  const { patterns } = results;
  const generated = {
    hooks: [],
    skills: [],
    rules: [],
    updated: []
  };

  // Generate hooks based on patterns
  if (patterns.frustration_triggers?.length > 0) {
    // Generate loop detector if retry frustration detected
    const hasRetryFrustration = patterns.frustration_triggers.some(
      f => /again|retry|loop|repeat/i.test(f.trigger)
    );
    if (hasRetryFrustration) {
      const hookPath = await generateHook(HOOK_TEMPLATES.loopDetector, targetDir);
      generated.hooks.push(hookPath);
    }
  }

  // Generate skills based on autonomy level
  if (patterns.autonomy_level?.label === "high") {
    const skillPath = await generateSkill(
      SKILL_TEMPLATES.quickAction,
      patterns,
      targetDir
    );
    generated.skills.push(skillPath);
  }

  // Generate domain context skill if expertise detected
  if (Object.keys(patterns.domain_expertise || {}).length > 0) {
    const skillPath = await generateSkill(
      SKILL_TEMPLATES.domainExpert,
      patterns,
      targetDir
    );
    generated.skills.push(skillPath);
  }

  // Generate platform-specific artifacts
  if (await fs.pathExists(path.join(targetDir, ".cursor"))) {
    const rulePath = await generateCursorRules(patterns, targetDir);
    generated.rules.push(rulePath);
  }

  if (await fs.pathExists(path.join(targetDir, ".opencode"))) {
    const hookPaths = await generateOpenCodeHooks(patterns, targetDir);
    generated.hooks.push(...hookPaths);
  }

  // Update CLAUDE.md
  const claudeUpdated = await updateClaudeMD(patterns, targetDir);
  if (claudeUpdated) {
    generated.updated.push("CLAUDE.md");
  }

  return generated;
}

/**
 * Clean up previously generated artifacts
 * @param {string} targetDir - Target directory
 * @returns {Promise<number>} - Number of files removed
 */
export async function cleanupGeneratedArtifacts(targetDir) {
  const generatedDir = path.join(targetDir, ".claude", "hooks", "slas", "generated");
  let count = 0;

  if (await fs.pathExists(generatedDir)) {
    const files = await fs.readdir(generatedDir);
    for (const file of files) {
      await fs.remove(path.join(generatedDir, file));
      count++;
    }
  }

  return count;
}

export default {
  generateArtifacts,
  generateHook,
  generateSkill,
  generateCursorRules,
  generateOpenCodeHooks,
  updateClaudeMD,
  cleanupGeneratedArtifacts,
  HOOK_TEMPLATES,
  SKILL_TEMPLATES
};
